// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RooCodeAnnouncer.Infrastructure;

#nullable disable

namespace RooCodeAnnouncer.Infrastructure.Migrations
{
    [DbContext(typeof(CodeAnnouncerDbContext))]
    partial class CodeAnnouncerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.1");

            modelBuilder.Entity("RooCodeAnnouncer.Infrastructure.Entities.PublishedItemCode", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rewards")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PublishedItemCodes");
                });
#pragma warning restore 612, 618
        }
    }
}
